#Define Project
substitutions:
  name: apollo-dev-2
  version:  "1"
  device_description: ${name} made by Apollo Automation - version ${version}.

packages:
  lcgreenwald.TnL-DEV-2: # name of package/project
    url: https://github.com/lcgreenwald/TnL-DEV-2 # url of the repository
    ref: dev # branch, tag or commit SHA
    files: [Integrations/ESPHome/TnL-DEV-2.yaml] # Path to config from base repo URL
    refresh: 1min # how often to sync updates from the remote url
  remote_package:
    url: https://github.com/lcgreenwald/TnL-DEV-2/
    ref: main
    files:
#      - Integrations/ESPHome/MyCustom.yaml
      - Integrations/ESPHome/InstantAQI.yaml
    refresh: 1min

esphome:
  name: "${name}"
  friendly_name: Apollo DEV-2
  comment: Apollo DEV-2
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.DEV-2"
    version: "${version}"

# Define Board
esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret apollo-dev-2-api-key

ota:
  - platform: esphome
    password: !secret apollo-dev-2-ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apollo-Dev-2 Fallback Hotspot"
    password: !secret wifi_password

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.195
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.1.181
    dns2: 192.168.1.107

captive_portal:

web_server:
  port: 80

#onboard LED using pin GPIO3 as shown below
light:
  - platform: esp32_rmt_led_strip
    id: rgb_onboard_light
    name: "RGB Onboard Light"
    pin: GPIO8
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 100
          

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${name} IP"
      icon: "mdi:ip-outline"
