packages:
  lcgreenwald.TnL-DEV-2: # name of package/project
    url: https://github.com/lcgreenwald/TnL-DEV-2 # url of the repository
    ref: dev # branch, tag or commit SHA
    files: [Integrations/ESPHome/TnL-core.yaml] # Path to config from base repo URL
    refresh: 1min # how often to sync updates from the remote url
  remote_package:
    url: https://github.com/lcgreenwald/TnL-DEV-2/
    ref: main
    files: 
      - Integrations/ESPHome/TnL-SEN66.yaml
      - Integrations/ESPHome/TnL-InstantAQI.yaml
    refresh: 1min
